# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c26379e731f4171e931c666bc184dd7a64c3f3dac3492657a83aa0f691e84580c4c1abffe31ca2d8a9560ded0518a66180586aed29510d09d6caa7c418741d6

test:
  secret_key_base: da5c54cd713aedeff521c51b2a96419c434ce999c5afc4bbc6edfb9b111ba7fc8b863a69e29f48722196a946c137d06511e2e3a1e38b803dad1ee4d63c206672

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
